name: ssh_app
description: Flutter SSH Server & Client Application
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartssh2: ^2.9.0
  xterm: ^4.0.0
  flutter_pty: ^0.4.0
  network_info_plus: ^8.1.0
  path_provider: ^2.1.4
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.5
  flutter_native_splash: ^2.3.6
  pointycastle: ^4.0.0
  crypto: ^3.0.3
  uuid: ^4.3.3
  share_plus: ^13.1.0
  file_picker: ^12.0.0-beta.4
  google_fonts: ^8.1.0
  opencode_api: ^1.0.0
  dio: ^5.8.0
  flutter_secure_storage: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: any

flutter:
  uses-material-design: true
  assets:
    - assets/
